package com.uflycn.uoperation.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.uflycn.uoperation.bean.AssistRecord;
import com.uflycn.uoperation.bean.BrokenDocument;
import com.uflycn.uoperation.bean.BrokenInspectRecord;
import com.uflycn.uoperation.bean.DayPlan;
import com.uflycn.uoperation.bean.DayPlanDetail;
import com.uflycn.uoperation.bean.DefectBean;
import com.uflycn.uoperation.bean.DefectDeleteRecord;
import com.uflycn.uoperation.bean.DefectRemark;
import com.uflycn.uoperation.bean.DefectType;
import com.uflycn.uoperation.bean.Document;
import com.uflycn.uoperation.bean.EarthingResistance;
import com.uflycn.uoperation.bean.Gridline;
import com.uflycn.uoperation.bean.IceCover;
import com.uflycn.uoperation.bean.ImagePaths;
import com.uflycn.uoperation.bean.InfraredTemperature;
import com.uflycn.uoperation.bean.InPlace;
import com.uflycn.uoperation.bean.ItemDetail;
import com.uflycn.uoperation.bean.LineCrossDelete;
import com.uflycn.uoperation.bean.LineCrossEntity;
import com.uflycn.uoperation.bean.OptTensilePointTemperature;
import com.uflycn.uoperation.bean.Organizition;
import com.uflycn.uoperation.bean.PatrolTrack;
import com.uflycn.uoperation.bean.ProjectEntity;
import com.uflycn.uoperation.bean.ProjectInspection;
import com.uflycn.uoperation.bean.RecordSyncInfo;
import com.uflycn.uoperation.bean.Role;
import com.uflycn.uoperation.bean.RoleMenuData;
import com.uflycn.uoperation.bean.Tower;
import com.uflycn.uoperation.bean.TowerChange;
import com.uflycn.uoperation.bean.TreeDefectPointBean;
import com.uflycn.uoperation.bean.User;
import com.uflycn.uoperation.bean.UserRole;
import com.uflycn.uoperation.bean.VirtualTower;
import com.uflycn.uoperation.bean.WorksheetApanageTask;
import com.uflycn.uoperation.bean.WorkSheetTask;
import com.uflycn.uoperation.bean.ZeroDetection;

import com.uflycn.uoperation.greendao.AssistRecordDao;
import com.uflycn.uoperation.greendao.BrokenDocumentDao;
import com.uflycn.uoperation.greendao.BrokenInspectRecordDao;
import com.uflycn.uoperation.greendao.DayPlanDao;
import com.uflycn.uoperation.greendao.DayPlanDetailDao;
import com.uflycn.uoperation.greendao.DefectBeanDao;
import com.uflycn.uoperation.greendao.DefectDeleteRecordDao;
import com.uflycn.uoperation.greendao.DefectRemarkDao;
import com.uflycn.uoperation.greendao.DefectTypeDao;
import com.uflycn.uoperation.greendao.DocumentDao;
import com.uflycn.uoperation.greendao.EarthingResistanceDao;
import com.uflycn.uoperation.greendao.GridlineDao;
import com.uflycn.uoperation.greendao.IceCoverDao;
import com.uflycn.uoperation.greendao.ImagePathsDao;
import com.uflycn.uoperation.greendao.InfraredTemperatureDao;
import com.uflycn.uoperation.greendao.InPlaceDao;
import com.uflycn.uoperation.greendao.ItemDetailDao;
import com.uflycn.uoperation.greendao.LineCrossDeleteDao;
import com.uflycn.uoperation.greendao.LineCrossEntityDao;
import com.uflycn.uoperation.greendao.OptTensilePointTemperatureDao;
import com.uflycn.uoperation.greendao.OrganizitionDao;
import com.uflycn.uoperation.greendao.PatrolTrackDao;
import com.uflycn.uoperation.greendao.ProjectEntityDao;
import com.uflycn.uoperation.greendao.ProjectInspectionDao;
import com.uflycn.uoperation.greendao.RecordSyncInfoDao;
import com.uflycn.uoperation.greendao.RoleDao;
import com.uflycn.uoperation.greendao.RoleMenuDataDao;
import com.uflycn.uoperation.greendao.TowerDao;
import com.uflycn.uoperation.greendao.TowerChangeDao;
import com.uflycn.uoperation.greendao.TreeDefectPointBeanDao;
import com.uflycn.uoperation.greendao.UserDao;
import com.uflycn.uoperation.greendao.UserRoleDao;
import com.uflycn.uoperation.greendao.VirtualTowerDao;
import com.uflycn.uoperation.greendao.WorksheetApanageTaskDao;
import com.uflycn.uoperation.greendao.WorkSheetTaskDao;
import com.uflycn.uoperation.greendao.ZeroDetectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig assistRecordDaoConfig;
    private final DaoConfig brokenDocumentDaoConfig;
    private final DaoConfig brokenInspectRecordDaoConfig;
    private final DaoConfig dayPlanDaoConfig;
    private final DaoConfig dayPlanDetailDaoConfig;
    private final DaoConfig defectBeanDaoConfig;
    private final DaoConfig defectDeleteRecordDaoConfig;
    private final DaoConfig defectRemarkDaoConfig;
    private final DaoConfig defectTypeDaoConfig;
    private final DaoConfig documentDaoConfig;
    private final DaoConfig earthingResistanceDaoConfig;
    private final DaoConfig gridlineDaoConfig;
    private final DaoConfig iceCoverDaoConfig;
    private final DaoConfig imagePathsDaoConfig;
    private final DaoConfig infraredTemperatureDaoConfig;
    private final DaoConfig inPlaceDaoConfig;
    private final DaoConfig itemDetailDaoConfig;
    private final DaoConfig lineCrossDeleteDaoConfig;
    private final DaoConfig lineCrossEntityDaoConfig;
    private final DaoConfig optTensilePointTemperatureDaoConfig;
    private final DaoConfig organizitionDaoConfig;
    private final DaoConfig patrolTrackDaoConfig;
    private final DaoConfig projectEntityDaoConfig;
    private final DaoConfig projectInspectionDaoConfig;
    private final DaoConfig recordSyncInfoDaoConfig;
    private final DaoConfig roleDaoConfig;
    private final DaoConfig roleMenuDataDaoConfig;
    private final DaoConfig towerDaoConfig;
    private final DaoConfig towerChangeDaoConfig;
    private final DaoConfig treeDefectPointBeanDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig userRoleDaoConfig;
    private final DaoConfig virtualTowerDaoConfig;
    private final DaoConfig worksheetApanageTaskDaoConfig;
    private final DaoConfig workSheetTaskDaoConfig;
    private final DaoConfig zeroDetectionDaoConfig;

    private final AssistRecordDao assistRecordDao;
    private final BrokenDocumentDao brokenDocumentDao;
    private final BrokenInspectRecordDao brokenInspectRecordDao;
    private final DayPlanDao dayPlanDao;
    private final DayPlanDetailDao dayPlanDetailDao;
    private final DefectBeanDao defectBeanDao;
    private final DefectDeleteRecordDao defectDeleteRecordDao;
    private final DefectRemarkDao defectRemarkDao;
    private final DefectTypeDao defectTypeDao;
    private final DocumentDao documentDao;
    private final EarthingResistanceDao earthingResistanceDao;
    private final GridlineDao gridlineDao;
    private final IceCoverDao iceCoverDao;
    private final ImagePathsDao imagePathsDao;
    private final InfraredTemperatureDao infraredTemperatureDao;
    private final InPlaceDao inPlaceDao;
    private final ItemDetailDao itemDetailDao;
    private final LineCrossDeleteDao lineCrossDeleteDao;
    private final LineCrossEntityDao lineCrossEntityDao;
    private final OptTensilePointTemperatureDao optTensilePointTemperatureDao;
    private final OrganizitionDao organizitionDao;
    private final PatrolTrackDao patrolTrackDao;
    private final ProjectEntityDao projectEntityDao;
    private final ProjectInspectionDao projectInspectionDao;
    private final RecordSyncInfoDao recordSyncInfoDao;
    private final RoleDao roleDao;
    private final RoleMenuDataDao roleMenuDataDao;
    private final TowerDao towerDao;
    private final TowerChangeDao towerChangeDao;
    private final TreeDefectPointBeanDao treeDefectPointBeanDao;
    private final UserDao userDao;
    private final UserRoleDao userRoleDao;
    private final VirtualTowerDao virtualTowerDao;
    private final WorksheetApanageTaskDao worksheetApanageTaskDao;
    private final WorkSheetTaskDao workSheetTaskDao;
    private final ZeroDetectionDao zeroDetectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        assistRecordDaoConfig = daoConfigMap.get(AssistRecordDao.class).clone();
        assistRecordDaoConfig.initIdentityScope(type);

        brokenDocumentDaoConfig = daoConfigMap.get(BrokenDocumentDao.class).clone();
        brokenDocumentDaoConfig.initIdentityScope(type);

        brokenInspectRecordDaoConfig = daoConfigMap.get(BrokenInspectRecordDao.class).clone();
        brokenInspectRecordDaoConfig.initIdentityScope(type);

        dayPlanDaoConfig = daoConfigMap.get(DayPlanDao.class).clone();
        dayPlanDaoConfig.initIdentityScope(type);

        dayPlanDetailDaoConfig = daoConfigMap.get(DayPlanDetailDao.class).clone();
        dayPlanDetailDaoConfig.initIdentityScope(type);

        defectBeanDaoConfig = daoConfigMap.get(DefectBeanDao.class).clone();
        defectBeanDaoConfig.initIdentityScope(type);

        defectDeleteRecordDaoConfig = daoConfigMap.get(DefectDeleteRecordDao.class).clone();
        defectDeleteRecordDaoConfig.initIdentityScope(type);

        defectRemarkDaoConfig = daoConfigMap.get(DefectRemarkDao.class).clone();
        defectRemarkDaoConfig.initIdentityScope(type);

        defectTypeDaoConfig = daoConfigMap.get(DefectTypeDao.class).clone();
        defectTypeDaoConfig.initIdentityScope(type);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        earthingResistanceDaoConfig = daoConfigMap.get(EarthingResistanceDao.class).clone();
        earthingResistanceDaoConfig.initIdentityScope(type);

        gridlineDaoConfig = daoConfigMap.get(GridlineDao.class).clone();
        gridlineDaoConfig.initIdentityScope(type);

        iceCoverDaoConfig = daoConfigMap.get(IceCoverDao.class).clone();
        iceCoverDaoConfig.initIdentityScope(type);

        imagePathsDaoConfig = daoConfigMap.get(ImagePathsDao.class).clone();
        imagePathsDaoConfig.initIdentityScope(type);

        infraredTemperatureDaoConfig = daoConfigMap.get(InfraredTemperatureDao.class).clone();
        infraredTemperatureDaoConfig.initIdentityScope(type);

        inPlaceDaoConfig = daoConfigMap.get(InPlaceDao.class).clone();
        inPlaceDaoConfig.initIdentityScope(type);

        itemDetailDaoConfig = daoConfigMap.get(ItemDetailDao.class).clone();
        itemDetailDaoConfig.initIdentityScope(type);

        lineCrossDeleteDaoConfig = daoConfigMap.get(LineCrossDeleteDao.class).clone();
        lineCrossDeleteDaoConfig.initIdentityScope(type);

        lineCrossEntityDaoConfig = daoConfigMap.get(LineCrossEntityDao.class).clone();
        lineCrossEntityDaoConfig.initIdentityScope(type);

        optTensilePointTemperatureDaoConfig = daoConfigMap.get(OptTensilePointTemperatureDao.class).clone();
        optTensilePointTemperatureDaoConfig.initIdentityScope(type);

        organizitionDaoConfig = daoConfigMap.get(OrganizitionDao.class).clone();
        organizitionDaoConfig.initIdentityScope(type);

        patrolTrackDaoConfig = daoConfigMap.get(PatrolTrackDao.class).clone();
        patrolTrackDaoConfig.initIdentityScope(type);

        projectEntityDaoConfig = daoConfigMap.get(ProjectEntityDao.class).clone();
        projectEntityDaoConfig.initIdentityScope(type);

        projectInspectionDaoConfig = daoConfigMap.get(ProjectInspectionDao.class).clone();
        projectInspectionDaoConfig.initIdentityScope(type);

        recordSyncInfoDaoConfig = daoConfigMap.get(RecordSyncInfoDao.class).clone();
        recordSyncInfoDaoConfig.initIdentityScope(type);

        roleDaoConfig = daoConfigMap.get(RoleDao.class).clone();
        roleDaoConfig.initIdentityScope(type);

        roleMenuDataDaoConfig = daoConfigMap.get(RoleMenuDataDao.class).clone();
        roleMenuDataDaoConfig.initIdentityScope(type);

        towerDaoConfig = daoConfigMap.get(TowerDao.class).clone();
        towerDaoConfig.initIdentityScope(type);

        towerChangeDaoConfig = daoConfigMap.get(TowerChangeDao.class).clone();
        towerChangeDaoConfig.initIdentityScope(type);

        treeDefectPointBeanDaoConfig = daoConfigMap.get(TreeDefectPointBeanDao.class).clone();
        treeDefectPointBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userRoleDaoConfig = daoConfigMap.get(UserRoleDao.class).clone();
        userRoleDaoConfig.initIdentityScope(type);

        virtualTowerDaoConfig = daoConfigMap.get(VirtualTowerDao.class).clone();
        virtualTowerDaoConfig.initIdentityScope(type);

        worksheetApanageTaskDaoConfig = daoConfigMap.get(WorksheetApanageTaskDao.class).clone();
        worksheetApanageTaskDaoConfig.initIdentityScope(type);

        workSheetTaskDaoConfig = daoConfigMap.get(WorkSheetTaskDao.class).clone();
        workSheetTaskDaoConfig.initIdentityScope(type);

        zeroDetectionDaoConfig = daoConfigMap.get(ZeroDetectionDao.class).clone();
        zeroDetectionDaoConfig.initIdentityScope(type);

        assistRecordDao = new AssistRecordDao(assistRecordDaoConfig, this);
        brokenDocumentDao = new BrokenDocumentDao(brokenDocumentDaoConfig, this);
        brokenInspectRecordDao = new BrokenInspectRecordDao(brokenInspectRecordDaoConfig, this);
        dayPlanDao = new DayPlanDao(dayPlanDaoConfig, this);
        dayPlanDetailDao = new DayPlanDetailDao(dayPlanDetailDaoConfig, this);
        defectBeanDao = new DefectBeanDao(defectBeanDaoConfig, this);
        defectDeleteRecordDao = new DefectDeleteRecordDao(defectDeleteRecordDaoConfig, this);
        defectRemarkDao = new DefectRemarkDao(defectRemarkDaoConfig, this);
        defectTypeDao = new DefectTypeDao(defectTypeDaoConfig, this);
        documentDao = new DocumentDao(documentDaoConfig, this);
        earthingResistanceDao = new EarthingResistanceDao(earthingResistanceDaoConfig, this);
        gridlineDao = new GridlineDao(gridlineDaoConfig, this);
        iceCoverDao = new IceCoverDao(iceCoverDaoConfig, this);
        imagePathsDao = new ImagePathsDao(imagePathsDaoConfig, this);
        infraredTemperatureDao = new InfraredTemperatureDao(infraredTemperatureDaoConfig, this);
        inPlaceDao = new InPlaceDao(inPlaceDaoConfig, this);
        itemDetailDao = new ItemDetailDao(itemDetailDaoConfig, this);
        lineCrossDeleteDao = new LineCrossDeleteDao(lineCrossDeleteDaoConfig, this);
        lineCrossEntityDao = new LineCrossEntityDao(lineCrossEntityDaoConfig, this);
        optTensilePointTemperatureDao = new OptTensilePointTemperatureDao(optTensilePointTemperatureDaoConfig, this);
        organizitionDao = new OrganizitionDao(organizitionDaoConfig, this);
        patrolTrackDao = new PatrolTrackDao(patrolTrackDaoConfig, this);
        projectEntityDao = new ProjectEntityDao(projectEntityDaoConfig, this);
        projectInspectionDao = new ProjectInspectionDao(projectInspectionDaoConfig, this);
        recordSyncInfoDao = new RecordSyncInfoDao(recordSyncInfoDaoConfig, this);
        roleDao = new RoleDao(roleDaoConfig, this);
        roleMenuDataDao = new RoleMenuDataDao(roleMenuDataDaoConfig, this);
        towerDao = new TowerDao(towerDaoConfig, this);
        towerChangeDao = new TowerChangeDao(towerChangeDaoConfig, this);
        treeDefectPointBeanDao = new TreeDefectPointBeanDao(treeDefectPointBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        userRoleDao = new UserRoleDao(userRoleDaoConfig, this);
        virtualTowerDao = new VirtualTowerDao(virtualTowerDaoConfig, this);
        worksheetApanageTaskDao = new WorksheetApanageTaskDao(worksheetApanageTaskDaoConfig, this);
        workSheetTaskDao = new WorkSheetTaskDao(workSheetTaskDaoConfig, this);
        zeroDetectionDao = new ZeroDetectionDao(zeroDetectionDaoConfig, this);

        registerDao(AssistRecord.class, assistRecordDao);
        registerDao(BrokenDocument.class, brokenDocumentDao);
        registerDao(BrokenInspectRecord.class, brokenInspectRecordDao);
        registerDao(DayPlan.class, dayPlanDao);
        registerDao(DayPlanDetail.class, dayPlanDetailDao);
        registerDao(DefectBean.class, defectBeanDao);
        registerDao(DefectDeleteRecord.class, defectDeleteRecordDao);
        registerDao(DefectRemark.class, defectRemarkDao);
        registerDao(DefectType.class, defectTypeDao);
        registerDao(Document.class, documentDao);
        registerDao(EarthingResistance.class, earthingResistanceDao);
        registerDao(Gridline.class, gridlineDao);
        registerDao(IceCover.class, iceCoverDao);
        registerDao(ImagePaths.class, imagePathsDao);
        registerDao(InfraredTemperature.class, infraredTemperatureDao);
        registerDao(InPlace.class, inPlaceDao);
        registerDao(ItemDetail.class, itemDetailDao);
        registerDao(LineCrossDelete.class, lineCrossDeleteDao);
        registerDao(LineCrossEntity.class, lineCrossEntityDao);
        registerDao(OptTensilePointTemperature.class, optTensilePointTemperatureDao);
        registerDao(Organizition.class, organizitionDao);
        registerDao(PatrolTrack.class, patrolTrackDao);
        registerDao(ProjectEntity.class, projectEntityDao);
        registerDao(ProjectInspection.class, projectInspectionDao);
        registerDao(RecordSyncInfo.class, recordSyncInfoDao);
        registerDao(Role.class, roleDao);
        registerDao(RoleMenuData.class, roleMenuDataDao);
        registerDao(Tower.class, towerDao);
        registerDao(TowerChange.class, towerChangeDao);
        registerDao(TreeDefectPointBean.class, treeDefectPointBeanDao);
        registerDao(User.class, userDao);
        registerDao(UserRole.class, userRoleDao);
        registerDao(VirtualTower.class, virtualTowerDao);
        registerDao(WorksheetApanageTask.class, worksheetApanageTaskDao);
        registerDao(WorkSheetTask.class, workSheetTaskDao);
        registerDao(ZeroDetection.class, zeroDetectionDao);
    }
    
    public void clear() {
        assistRecordDaoConfig.clearIdentityScope();
        brokenDocumentDaoConfig.clearIdentityScope();
        brokenInspectRecordDaoConfig.clearIdentityScope();
        dayPlanDaoConfig.clearIdentityScope();
        dayPlanDetailDaoConfig.clearIdentityScope();
        defectBeanDaoConfig.clearIdentityScope();
        defectDeleteRecordDaoConfig.clearIdentityScope();
        defectRemarkDaoConfig.clearIdentityScope();
        defectTypeDaoConfig.clearIdentityScope();
        documentDaoConfig.clearIdentityScope();
        earthingResistanceDaoConfig.clearIdentityScope();
        gridlineDaoConfig.clearIdentityScope();
        iceCoverDaoConfig.clearIdentityScope();
        imagePathsDaoConfig.clearIdentityScope();
        infraredTemperatureDaoConfig.clearIdentityScope();
        inPlaceDaoConfig.clearIdentityScope();
        itemDetailDaoConfig.clearIdentityScope();
        lineCrossDeleteDaoConfig.clearIdentityScope();
        lineCrossEntityDaoConfig.clearIdentityScope();
        optTensilePointTemperatureDaoConfig.clearIdentityScope();
        organizitionDaoConfig.clearIdentityScope();
        patrolTrackDaoConfig.clearIdentityScope();
        projectEntityDaoConfig.clearIdentityScope();
        projectInspectionDaoConfig.clearIdentityScope();
        recordSyncInfoDaoConfig.clearIdentityScope();
        roleDaoConfig.clearIdentityScope();
        roleMenuDataDaoConfig.clearIdentityScope();
        towerDaoConfig.clearIdentityScope();
        towerChangeDaoConfig.clearIdentityScope();
        treeDefectPointBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        userRoleDaoConfig.clearIdentityScope();
        virtualTowerDaoConfig.clearIdentityScope();
        worksheetApanageTaskDaoConfig.clearIdentityScope();
        workSheetTaskDaoConfig.clearIdentityScope();
        zeroDetectionDaoConfig.clearIdentityScope();
    }

    public AssistRecordDao getAssistRecordDao() {
        return assistRecordDao;
    }

    public BrokenDocumentDao getBrokenDocumentDao() {
        return brokenDocumentDao;
    }

    public BrokenInspectRecordDao getBrokenInspectRecordDao() {
        return brokenInspectRecordDao;
    }

    public DayPlanDao getDayPlanDao() {
        return dayPlanDao;
    }

    public DayPlanDetailDao getDayPlanDetailDao() {
        return dayPlanDetailDao;
    }

    public DefectBeanDao getDefectBeanDao() {
        return defectBeanDao;
    }

    public DefectDeleteRecordDao getDefectDeleteRecordDao() {
        return defectDeleteRecordDao;
    }

    public DefectRemarkDao getDefectRemarkDao() {
        return defectRemarkDao;
    }

    public DefectTypeDao getDefectTypeDao() {
        return defectTypeDao;
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public EarthingResistanceDao getEarthingResistanceDao() {
        return earthingResistanceDao;
    }

    public GridlineDao getGridlineDao() {
        return gridlineDao;
    }

    public IceCoverDao getIceCoverDao() {
        return iceCoverDao;
    }

    public ImagePathsDao getImagePathsDao() {
        return imagePathsDao;
    }

    public InfraredTemperatureDao getInfraredTemperatureDao() {
        return infraredTemperatureDao;
    }

    public InPlaceDao getInPlaceDao() {
        return inPlaceDao;
    }

    public ItemDetailDao getItemDetailDao() {
        return itemDetailDao;
    }

    public LineCrossDeleteDao getLineCrossDeleteDao() {
        return lineCrossDeleteDao;
    }

    public LineCrossEntityDao getLineCrossEntityDao() {
        return lineCrossEntityDao;
    }

    public OptTensilePointTemperatureDao getOptTensilePointTemperatureDao() {
        return optTensilePointTemperatureDao;
    }

    public OrganizitionDao getOrganizitionDao() {
        return organizitionDao;
    }

    public PatrolTrackDao getPatrolTrackDao() {
        return patrolTrackDao;
    }

    public ProjectEntityDao getProjectEntityDao() {
        return projectEntityDao;
    }

    public ProjectInspectionDao getProjectInspectionDao() {
        return projectInspectionDao;
    }

    public RecordSyncInfoDao getRecordSyncInfoDao() {
        return recordSyncInfoDao;
    }

    public RoleDao getRoleDao() {
        return roleDao;
    }

    public RoleMenuDataDao getRoleMenuDataDao() {
        return roleMenuDataDao;
    }

    public TowerDao getTowerDao() {
        return towerDao;
    }

    public TowerChangeDao getTowerChangeDao() {
        return towerChangeDao;
    }

    public TreeDefectPointBeanDao getTreeDefectPointBeanDao() {
        return treeDefectPointBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserRoleDao getUserRoleDao() {
        return userRoleDao;
    }

    public VirtualTowerDao getVirtualTowerDao() {
        return virtualTowerDao;
    }

    public WorksheetApanageTaskDao getWorksheetApanageTaskDao() {
        return worksheetApanageTaskDao;
    }

    public WorkSheetTaskDao getWorkSheetTaskDao() {
        return workSheetTaskDao;
    }

    public ZeroDetectionDao getZeroDetectionDao() {
        return zeroDetectionDao;
    }

}
