package com.uflycn.uoperation.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.uflycn.uoperation.bean.InPlace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "operation_InPlace".
*/
public class InPlaceDao extends AbstractDao<InPlace, Long> {

    public static final String TABLENAME = "operation_InPlace";

    /**
     * Properties of entity InPlace.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SysInPlaceId = new Property(0, Long.class, "sysInPlaceId", true, "_id");
        public final static Property SysUserId = new Property(1, String.class, "sysUserId", false, "SYS_USER_ID");
        public final static Property Longitude = new Property(2, double.class, "Longitude", false, "LONGITUDE");
        public final static Property Latitude = new Property(3, double.class, "Latitude", false, "LATITUDE");
        public final static Property Altitude = new Property(4, double.class, "Altitude", false, "ALTITUDE");
        public final static Property SysTowerId = new Property(5, int.class, "sysTowerId", false, "SYS_TOWER_ID");
        public final static Property NearTowerId = new Property(6, int.class, "nearTowerId", false, "NEAR_TOWER_ID");
        public final static Property PatrolType = new Property(7, String.class, "PatrolType", false, "PATROL_TYPE");
        public final static Property CreateDate = new Property(8, String.class, "CreateDate", false, "CREATE_DATE");
        public final static Property UploadFlag = new Property(9, int.class, "UploadFlag", false, "UPLOAD_FLAG");
        public final static Property PlanDailyPlanSectionIDs = new Property(10, String.class, "PlanDailyPlanSectionIDs", false, "PLAN_DAILY_PLAN_SECTION_IDS");
        public final static Property SysPatrolExecutionID = new Property(11, String.class, "sysPatrolExecutionID", false, "SYS_PATROL_EXECUTION_ID");
    }


    public InPlaceDao(DaoConfig config) {
        super(config);
    }
    
    public InPlaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"operation_InPlace\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: sysInPlaceId
                "\"SYS_USER_ID\" TEXT," + // 1: sysUserId
                "\"LONGITUDE\" REAL NOT NULL ," + // 2: Longitude
                "\"LATITUDE\" REAL NOT NULL ," + // 3: Latitude
                "\"ALTITUDE\" REAL NOT NULL ," + // 4: Altitude
                "\"SYS_TOWER_ID\" INTEGER NOT NULL ," + // 5: sysTowerId
                "\"NEAR_TOWER_ID\" INTEGER NOT NULL ," + // 6: nearTowerId
                "\"PATROL_TYPE\" TEXT," + // 7: PatrolType
                "\"CREATE_DATE\" TEXT," + // 8: CreateDate
                "\"UPLOAD_FLAG\" INTEGER NOT NULL ," + // 9: UploadFlag
                "\"PLAN_DAILY_PLAN_SECTION_IDS\" TEXT," + // 10: PlanDailyPlanSectionIDs
                "\"SYS_PATROL_EXECUTION_ID\" TEXT);"); // 11: sysPatrolExecutionID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"operation_InPlace\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, InPlace entity) {
        stmt.clearBindings();
 
        Long sysInPlaceId = entity.getSysInPlaceId();
        if (sysInPlaceId != null) {
            stmt.bindLong(1, sysInPlaceId);
        }
 
        String sysUserId = entity.getSysUserId();
        if (sysUserId != null) {
            stmt.bindString(2, sysUserId);
        }
        stmt.bindDouble(3, entity.getLongitude());
        stmt.bindDouble(4, entity.getLatitude());
        stmt.bindDouble(5, entity.getAltitude());
        stmt.bindLong(6, entity.getSysTowerId());
        stmt.bindLong(7, entity.getNearTowerId());
 
        String PatrolType = entity.getPatrolType();
        if (PatrolType != null) {
            stmt.bindString(8, PatrolType);
        }
 
        String CreateDate = entity.getCreateDate();
        if (CreateDate != null) {
            stmt.bindString(9, CreateDate);
        }
        stmt.bindLong(10, entity.getUploadFlag());
 
        String PlanDailyPlanSectionIDs = entity.getPlanDailyPlanSectionIDs();
        if (PlanDailyPlanSectionIDs != null) {
            stmt.bindString(11, PlanDailyPlanSectionIDs);
        }
 
        String sysPatrolExecutionID = entity.getSysPatrolExecutionID();
        if (sysPatrolExecutionID != null) {
            stmt.bindString(12, sysPatrolExecutionID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, InPlace entity) {
        stmt.clearBindings();
 
        Long sysInPlaceId = entity.getSysInPlaceId();
        if (sysInPlaceId != null) {
            stmt.bindLong(1, sysInPlaceId);
        }
 
        String sysUserId = entity.getSysUserId();
        if (sysUserId != null) {
            stmt.bindString(2, sysUserId);
        }
        stmt.bindDouble(3, entity.getLongitude());
        stmt.bindDouble(4, entity.getLatitude());
        stmt.bindDouble(5, entity.getAltitude());
        stmt.bindLong(6, entity.getSysTowerId());
        stmt.bindLong(7, entity.getNearTowerId());
 
        String PatrolType = entity.getPatrolType();
        if (PatrolType != null) {
            stmt.bindString(8, PatrolType);
        }
 
        String CreateDate = entity.getCreateDate();
        if (CreateDate != null) {
            stmt.bindString(9, CreateDate);
        }
        stmt.bindLong(10, entity.getUploadFlag());
 
        String PlanDailyPlanSectionIDs = entity.getPlanDailyPlanSectionIDs();
        if (PlanDailyPlanSectionIDs != null) {
            stmt.bindString(11, PlanDailyPlanSectionIDs);
        }
 
        String sysPatrolExecutionID = entity.getSysPatrolExecutionID();
        if (sysPatrolExecutionID != null) {
            stmt.bindString(12, sysPatrolExecutionID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public InPlace readEntity(Cursor cursor, int offset) {
        InPlace entity = new InPlace( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // sysInPlaceId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sysUserId
            cursor.getDouble(offset + 2), // Longitude
            cursor.getDouble(offset + 3), // Latitude
            cursor.getDouble(offset + 4), // Altitude
            cursor.getInt(offset + 5), // sysTowerId
            cursor.getInt(offset + 6), // nearTowerId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // PatrolType
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // CreateDate
            cursor.getInt(offset + 9), // UploadFlag
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // PlanDailyPlanSectionIDs
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // sysPatrolExecutionID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, InPlace entity, int offset) {
        entity.setSysInPlaceId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSysUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLongitude(cursor.getDouble(offset + 2));
        entity.setLatitude(cursor.getDouble(offset + 3));
        entity.setAltitude(cursor.getDouble(offset + 4));
        entity.setSysTowerId(cursor.getInt(offset + 5));
        entity.setNearTowerId(cursor.getInt(offset + 6));
        entity.setPatrolType(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreateDate(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUploadFlag(cursor.getInt(offset + 9));
        entity.setPlanDailyPlanSectionIDs(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSysPatrolExecutionID(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(InPlace entity, long rowId) {
        entity.setSysInPlaceId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(InPlace entity) {
        if(entity != null) {
            return entity.getSysInPlaceId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(InPlace entity) {
        return entity.getSysInPlaceId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
